export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGIN_CLEAN = "ADMIN_LOGIN_CLEAN";

export const CHECK_ADMIN_LOGIN_STATUS = "CHECK_ADMIN_LOGIN_STATUS";
export const CHECK_ADMIN_LOGIN_STATUS_SUCCESS =
  "CHECK_ADMIN_LOGIN_STATUS_SUCCESS";
export const CHECK_ADMIN_LOGIN_STATUS_FAIL = "CHECK_ADMIN_LOGIN_STATUS_FAIL";
export const CHECK_ADMIN_LOGIN_STATUS_CLEAN = "CHECK_ADMIN_LOGIN_STATUS_CLEAN";

export const ADMIN_ADD_EMPLOYEE = "ADMIN_ADD_EMPLOYEE";
export const ADMIN_ADD_EMPLOYEE_SUCCESS = "ADMIN_ADD_EMPLOYEE_SUCCESS";
export const ADMIN_ADD_EMPLOYEE_FAILURE = "ADMIN_ADD_EMPLOYEE_FAILURE";
export const ADMIN_ADD_EMPLOYEE_CLEAR = "ADMIN_ADD_EMPLOYEE_CLEAR";

export const ADMIN_FETCH_EMPLOYEES = "ADMIN_FETCH_EMPLOYEES";
export const ADMIN_FETCH_EMPLOYEES_SUCCESS = "ADMIN_FETCH_EMPLOYEES_SUCCESS";
export const ADMIN_FETCH_EMPLOYEES_FAILURE = "ADMIN_FETCH_EMPLOYEES_FAILURE";
export const ADMIN_FETCH_EMPLOYEES_CLEAN = "ADMIN_FETCH_EMPLOYEES_CLEAN";

export const ADMIN_EDIT_EMPLOYEE = "ADMIN_EDIT_EMPLOYEE";
export const ADMIN_EDIT_EMPLOYEE_SUCCESS = "ADMIN_EDIT_EMPLOYEE_SUCCESS";
export const ADMIN_EDIT_EMPLOYEE_FAILURE = "ADMIN_EDIT_EMPLOYEE_FAILURE";
export const ADMIN_EDIT_EMPLOYEE_CLEAN = "ADMIN_EDIT_EMPLOYEE_CLEAN";

export const ADMIN_CHANGE_EMPLOYEE_PASSWORD = "ADMIN_CHANGE_EMPLOYEE_PASSWORD";
export const ADMIN_CHANGE_EMPLOYEE_PASSWORD_SUCCESS =
  "ADMIN_CHANGE_EMPLOYEE_PASSWORD_SUCCESS";
export const ADMIN_CHANGE_EMPLOYEE_PASSWORD_FAILURE =
  "ADMIN_CHANGE_EMPLOYEE_PASSWORD_FAILURE";
export const ADMIN_CHANGE_EMPLOYEE_PASSWORD_CLEAN_ERROR =
  "ADMIN_CHANGE_EMPLOYEE_PASSWORD_CLEAN_ERROR";

export const ADMIN_DELETE_EMPLOYEE = "ADMIN_DELETE_EMPLOYEE";
export const ADMIN_DELETE_EMPLOYEE_SUCCESS = "ADMIN_DELETE_EMPLOYEE_SUCCESS";
export const ADMIN_DELETE_EMPLOYEE_FAILURE = "ADMIN_DELETE_EMPLOYEE_FAILURE";
export const ADMIN_DELETE_EMPLOYEE_CLEAN = "ADMIN_DELETE_EMPLOYEE_CLEAN";

export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
export const AMDIN_LOGOUT_SUCCESS = "AMDIN_LOGOUT_SUCCESS";
export const ADMIN_LOGOUT_FAILURE = "ADMIN_LOGOUT_FAILURE";
export const ADMIN_LOGOUT_CLEAN = "ADMIN_LOGOUT_CLEAN";
