export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";

export const ADMIN_ADD_EMPLOYEE = "ADMIN_ADD_EMPLOYEE";
export const ADMIN_ADD_EMPLOYEE_SUCCESS = "ADMIN_ADD_EMPLOYEE_SUCCESS";
export const ADMIN_ADD_EMPLOYEE_FAILURE = "ADMIN_ADD_EMPLOYEE_FAILURE";

export const ADMIN_FETCH_EMPLOYEES = "ADMIN_FETCH_EMPLOYEES";
export const ADMIN_FETCH_EMPLOYEES_SUCCESS = "ADMIN_FETCH_EMPLOYEES_SUCCESS";
export const ADMIN_FETCH_EMPLOYEES_FAILURE = "ADMIN_FETCH_EMPLOYEES_FAILURE";

export const ADMIN_EDIT_EMPLOYEE = "ADMIN_EDIT_EMPLOYEE";
export const ADMIN_EDIT_EMPLOYEE_SUCCESS = "ADMIN_EDIT_EMPLOYEE_SUCCESS";
export const ADMIN_EDIT_EMPLOYEE_FAILURE = "ADMIN_EDIT_EMPLOYEE_FAILURE";

export const ADMIN_CHANGE_EMPLOYEE_PASSWORD = "ADMIN_CHANGE_EMPLOYEE_PASSWORD";
export const ADMIN_CHANGE_EMPLOYEE_PASSWORD_SUCCESS =
  "ADMIN_CHANGE_EMPLOYEE_PASSWORD_SUCCESS";
export const ADMIN_CHANGE_EMPLOYEE_PASSWORD_FAILURE =
  "ADMIN_CHANGE_EMPLOYEE_PASSWORD_FAILURE";
