export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";

export const ADMIN_ADD_EMPLOYEE = "ADMIN_ADD_EMPLOYEE";
export const ADMIN_ADD_EMPLOYEE_SUCCESS = "ADMIN_ADD_EMPLOYEE_SUCCESS";
export const ADMIN_ADD_EMPLOYEE_FAILURE = "ADMIN_ADD_EMPLOYEE_FAILURE";
