export const EMPLOYEE_LOGIN = "EMPLOYEE_LOGIN";
export const EMPLOYEE_LOGIN_SUCCESS = "EMPLOYEE_LOGIN_SUCCESS";
export const EMPLOYEE_LOGIN_FAIL = "EMPLOYEE_LOGIN_FAIL";
export const EMPLOYEE_LOGIN_CLEAN = "EMPLOYEE_LOGIN_CLEAN";

export const EMPLOYEE_FETCH_USERS = "EMPLOYEE_FETCH_USERS";
export const EMPLOYEE_FETCH_USERS_SUCCESS = "EMPLOYEE_FETCH_USERS_SUCCESS";
export const EMPLOYEE_FETCH_USERS_FAIL = "EMPLOYEE_FETCH_USERS_FAIL";
export const EMPLOYEE_FETCH_USERS_CLEAN = "EMPLOYEE_FETCH_USERS_CLEAN";

export const EMPLOYEE_LOGOUT = "EMPLOYEE_LOGOUT";
export const EMPLOYEE_LOGOUT_SUCCESS = "EMPLOYEE_LOGOUT_SUCCESS";
export const EMPLOYEE_LOGOUT_FAIL = "EMPLOYEE_LOGOUT_FAIL";
export const EMPLOYEE_LOGOUT_CLEAN = "EMPLOYEE_LOGOUT_CLEAN";
