export const EMPLOYEE_LOGIN = "EMPLOYEE_LOGIN";
export const EMPLOYEE_LOGIN_SUCCESS = "EMPLOYEE_LOGIN_SUCCESS";
export const EMPLOYEE_LOGIN_FAIL = "EMPLOYEE_LOGIN_FAIL";
export const EMPLOYEE_LOGIN_CLEAN = "EMPLOYEE_LOGIN_CLEAN";

export const CHECK_EMPLOYEE_LOGIN_STATUS = "CHECK_EMPLOYEE_LOGIN_STATUS";
export const CHECK_EMPLOYEE_LOGIN_STATUS_SUCCESS =
  "CHECK_EMPLOYEE_LOGIN_STATUS_SUCCESS";
export const CHECK_EMPLOYEE_LOGIN_STATUS_FAIL =
  "CHECK_EMPLOYEE_LOGIN_STATUS_FAIL";
export const CHECK_EMPLOYEE_LOGIN_STATUS_CLEAN =
  "CHECK_EMPLOYEE_LOGIN_STATUS_CLEAN";

export const EMPLOYEE_BY_ID = "EMPLOYEE_BY_ID";
export const EMPLOYEE_BY_ID_SUCCESS = "EMPLOYEE_BY_ID_SUCCESS";
export const EMPLOYEE_BY_ID_FAILURE = "EMPLOYEE_BY_ID_FAILURE";
export const EMPLOYEE_BY_ID_CLEAN = "EMPLOYEE_BY_ID_CLEAN";

export const EMPLOYEE_FETCH_USERS = "EMPLOYEE_FETCH_USERS";
export const EMPLOYEE_FETCH_USERS_SUCCESS = "EMPLOYEE_FETCH_USERS_SUCCESS";
export const EMPLOYEE_FETCH_USERS_FAIL = "EMPLOYEE_FETCH_USERS_FAIL";
export const EMPLOYEE_FETCH_USERS_CLEAN = "EMPLOYEE_FETCH_USERS_CLEAN";

export const EMPLOYEE_LOGOUT = "EMPLOYEE_LOGOUT";
export const EMPLOYEE_LOGOUT_SUCCESS = "EMPLOYEE_LOGOUT_SUCCESS";
export const EMPLOYEE_LOGOUT_FAIL = "EMPLOYEE_LOGOUT_FAIL";
export const EMPLOYEE_LOGOUT_CLEAN = "EMPLOYEE_LOGOUT_CLEAN";

export const FETCH_MOST_POPULAR_NFT = "FETCH_MOST_POPULAR_NFT";
export const FETCH_MOST_POPULAR_NFT_SUCCESS = "FETCH_MOST_POPULAR_NFT_SUCCESS";
export const FETCH_MOST_POPULAR_NFT_FAILURE = "FETCH_MOST_POPULAR_NFT_FAILURE";
export const FETCH_MOST_POPULAR_NFT_CLEAN = "FETCH_MOST_POPULAR_NFT_CLEAN";

export const NEWLY_MINTED_NFTS = "NEWLY_MINTED_NFTS";
export const NEWLY_MINTED_NFTS_SUCCESS = "NEWLY_MINTED_NFTS_SUCCESS";
export const NEWLY_MINTED_NFTS_FAILURE = "NEWLY_MINTED_NFTS_FAILURE";
export const NEWLY_MINTED_NFTS_CLEAN = "FETCH_MOST_POPULAR_NFT_CLEAN";

export const SEND_EMAIL = "SEND_EMAIL";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAILURE = "SEND_EMAIL_FAILURE";
export const SEND_EMAIL_CLEAN = "SEND_EMAIL_CLEAN";
